### ISSUE TITLE
Update design

### ISSUE THREAD

**Issue by craigmdennis** [closeio/making.close.com#26]
To be completed as part of #24 

![image](https://user-images.githubusercontent.com/725067/94149901-630fe600-fe70-11ea-8f49-23cbf6d19181.png)

https://www.figma.com/file/60gX55qEC13Y4Ol3w1y4qa/Initial-Design?node-id=1%3A2

**Comment by AlecRosenbaum** [comment]
I think @lukasmlady has been promoted to DevRel lol

I'm assuming this is just because of how it was made in figma, but just making sure.

**Comment by AlecRosenbaum** [comment]
Ah nvm, I see the screenshot in #24 with the correct authors.

Looks great!

**Comment by tsx** [comment]
:shipit:

**Comment by lukasmlady** [comment]
I'm OK with taking credit for all the articles
