### ISSUE TITLE
Cleanup .eslintrc.json

### ISSUE THREAD

**Issue by philfreo** [closeio/making.close.com#29]
> It's good that you tried to follow the same as our closeio repo, but some of this definitely doesn't belong (and will ultimately be cleaned up from the UI repo too). @lukasmlady Can you suggest a clean eslintrc that matches what we'd want for a new repo?
> 
> (Also related to my semicolon comment below)

_Originally posted by @philfreo in https://github.com/closeio/making.close.com/pull/24#discussion_r495945969_

https://github.com/closeio/making.close.com/blob/7417e0585844fc81fcca842152a996a3bf6ef5bd/.eslintrc.json#L29-L57

**Comment by lukasmlady** [comment]
The config looks good and in line with what we do in the Close app.

I'd drop _everything_ in the `global` part and add `__PATH_PREFIX__: true,` as it is mentioned in https://www.gatsbyjs.com/docs/eslint/.
