### ISSUE TITLE
Import some older blog posts

### ISSUE THREAD

**Issue by philfreo** [closeio/making.close.com#8]
We have had a few older blog posts on blog.close.com that would be good to duplicate here to populate a larger index of back content. Either import the actual content or just add a quote & link over to the main post.

- [x] https://blog.close.com/sweating-the-ui-ux-details-in-close-io-emails (and comments: https://news.ycombinator.com/item?id=5646828)
- [ ] https://blog.close.com/sales-data-search-writing-a-query-parser-ast-using-part-1
- [ ] https://blog.close.com/sales-data-search-writing-a-query-parser-ast-using
- [ ] https://blog.close.com/the-tech-stack-behind-close-io-sales-communication
- [ ] https://blog.close.com/the-startups-and-services-behind-closeio

**Comment by lukasmlady** [comment]
bump @philfreo

**Comment by philfreo** [comment]
@thomasst I imported your 2 old search parsing/AST posts in #8. I had to do a bunch of manual formatting cleanup and I wasn't sure how a couple parts were supposed to be formatted -- take a look when you get a chance and make any corrections needed:
https://github.com/closeio/making.close.com/blob/master/_posts/2013-04-17-query-parser-ast-pyparsing-elasticsearch-part-1/index.md
https://github.com/closeio/making.close.com/blob/master/_posts/2013-04-17-query-parser-ast-pyparsing-elasticsearch-part2/index.md
