### ISSUE TITLE
Google Crawl issue / JSON

### ISSUE THREAD

**Issue by philfreo** [closeio/making.close.com#91]
@nickpersico found an important issue regarding Google Crawl stats regarding our domain where they're spending too high a % crawling our product/eng blog here -- in particular some JSON. (In Slack I shared a Loom with more details)

What is this JSON?
How do we turn it off?

@closeio/frontend 

<img width="837" alt="Screen Shot 2022-08-24 at 3 59 46 PM" src="https://user-images.githubusercontent.com/97612/186522418-18d9a21c-2a99-4851-80bd-c0af784c23c1.png">

**Comment by nickpersico** [comment]
@buzinas @philfreo I tried to add the new `robots.txt` to Search Console and got this error:

<img width="1526" alt="CleanShot 2022-08-24 at 21 17 07@2x" src="https://user-images.githubusercontent.com/942973/186552436-13f1f1b0-f6c2-44ff-b935-84ba2d5b5805.png">

[Link](https://search.google.com/search-console/sitemaps/info-drilldown?resource_id=sc-domain:close.com&sitemap=https:%2F%2Fmaking.close.com%2Frobots.txt)

**Comment by philfreo** [comment]
That's not a sitemap file. It's a robots.txt. 

Let's discuss in slack (this is a public repo)
