### ISSUE TITLE
favicon should be transparent

### ISSUE THREAD

**Issue by philfreo** [closeio/making.close.com#99]
<img width="84" alt="Screenshot 2023-07-06 at 9 59 50 AM" src="https://github.com/closeio/making.close.com/assets/97612/986729f2-2ba1-4f94-98ae-4827f0c04b3b">

**Comment by ehernandez42** [comment]
I want to take a look at this, so I'm curious - where exactly do you see this on the site?

**Comment by rohmann** [comment]
I think that's because the favicon in the repo isn't actually used at all and it's getting setup with a gatsby plugin. I'll look into this after https://github.com/closeio/close-ui/issues/11105
